use crate::domain::{ApplicationKind, WindowId};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    Quit,
    Refresh,
    ToggleLauncher,
    CloseLauncher,
    MoveLauncherUp,
    MoveLauncherDown,
    ExecuteLauncherSelection,
    PaletteQueryPush(char),
    PaletteQueryBackspace,
    /// Run `!…` query from the command palette in a new terminal.
    RunPaletteShell,
    OpenApplication(ApplicationKind),
    CloseWindow,
    /// Focus the Nth window on the current workspace (1–9, left-to-right in the bar).
    FocusWindowSlot(u8),
    /// Wait for a follow-up digit (prefix chord — works inside host terminals).
    BeginWindowPick,
    CancelWindowPick,
    FocusWindow(WindowId),
    MinimizeWindow,
    ToggleMaximizeWindow,
    SwitchWorkspace(usize),
    MoveFileSelection(i32),
    OpenSelectedEntry,
    ToggleFileManagerHidden,
    ReloadFileManager,
    SelectFileManagerRow(WindowId, usize),
    FileManagerTogglePane,
    FileManagerGoHome,
    FileManagerGoBack,
    FileManagerGoUp,
    FileManagerPageScroll(i32),
    FileManagerSetSort(crate::app::SortColumn),
    SelectFileManagerPlace(WindowId, usize),
    ToggleInputDebug,
    MoveProcessSelection(i32),
    ProcessPageScroll(i32),
    ProcessFilterBegin,
    ProcessFilterPush(char),
    ProcessFilterBackspace,
    ProcessFilterEnd,
    ProcessKillSelected,
    FileManagerOpenInTerminal,
    FileManagerRequestDelete,
    FileManagerConfirmDelete,
    FileManagerCancelDialog,
    FileManagerBeginRename,
    FileManagerBeginCreate(crate::app::file_manager::CreateKind),
    FileManagerDialogPush(char),
    FileManagerDialogBackspace,
    FileManagerDialogCommit,
    SelectProcessRow(WindowId, usize),
}
